### ISSUE TITLE
[wiki] define ./src folder stucture plus admin module pages folder structure

### ISSUE THREAD

**Issue by brauliodiez** [MasterLemon2016/LeanMood#11]
In the wiki we have already defined a global project structure, we will start by implementing the lm-app > admin module (is something easy to get started low hanging fruit a good starting point).

We have to agree on the structure we will place under ./src , here is a proposal, could you please review it and add it to the wiki:

https://github.com/MasterLemon2016/LeanMood/wiki/solutions

Proposed structure:

_First level:_

```
+ src
|--+ common
|----+ components
|----+ actions
|--+ model
|--+ pages
|--+ reducers
|--+ rest-api
|--+ validations

```

_Second Level: (only admin module)_

+ pages
|-- + admin
|----- + home
|----- + training
|--------+ list
|--------+ detail
|----- + student
|--------+ list
|--------+ detail
|------+ permission

Third Level

+ pages
|--+ admin
|----+ training
|------+ list
|--------+ actions
|--------+ components
|--------+ containers
|----------*  listPageContainer.ts
|--------*  listPage.tsx
|--------*  index.ts

**Comment by linuxonrails** [comment]
Done.
