### ISSUE TITLE
Install and configure the unit testing infraestructure

### ISSUE THREAD

**Issue by brauliodiez** [MasterLemon2016/LeanMood#20]
Follow the steps from sample

https://github.com/Lemoncode/redux-by-sample/tree/master/12%20Testing%20Infrastructure

**Comment by franmolmedo** [comment]
Two questions:
  How about adding istanbul for testing coverage?
  Instead of karma, why not using mocha, jsdom, enzyme and chai, only?

**Comment by brauliodiez** [comment]
Sorry missed to add that on the case, already adding istabul for code coverage, following this:

https://github.com/Lemoncode/redux-by-sample/tree/master/16%20Code%20Coverage

There's already a commit with the basic infraestructure, if you want to take a sneak peak.

About karma, just using this because was easy to integrate with travis, keep it always running in watch mode, and easy to setup tests on several browsers (e.g. chrome and phantom). If there is a better way to do that (front end is running like hell), I'm open to replace it.  

A good starting point could be to create another sample for redux sample, we have already:

- karma/mocha/chai/sinon/istanbul: 

https://github.com/Lemoncode/redux-by-sample/tree/master/16%20Code%20Coverage

- jest:

https://github.com/Lemoncode/redux-by-sample/tree/master/11%20Testing_Jest


It would be great if you could create a:

17 jsdom_testing

you could take as starting point sample 09. That would be a great playground, and a goo guide to replace the testing infraestructure on the LeanMood project. What do you think?

**Comment by brauliodiez** [comment]
Forgot to say, thanks a lot for your feedback, really welcomed.

**Comment by brauliodiez** [comment]
@franmolmedo just added you as reviewer on the testing infraestructure branch. If you find areas that can be improved just go ahead and comment them.

**Comment by franmolmedo** [comment]
Ok!. I will try creating the test infrastructure using jsdom, enzyme, chai and mocha. Leave it up to me! :)

**Comment by brauliodiez** [comment]
Closing this issue right now will open a new one to include @franmolmedo proposal
