### ISSUE TITLE
Add Redux-Router support

### ISSUE THREAD

**Issue by brauliodiez** [MasterLemon2016/LeanMood#22]
Add support to react redux router, it's easy to add (once we have the reducers in place), you can take as guidance: 

https://github.com/Lemoncode/redux-by-sample/tree/master/06%20SimpleApp_Navigation

To install the redux-dev-tool plugin, check this page look for the google chrome link extension:

https://github.com/zalmoxisus/redux-devtools-extension

**Comment by brauliodiez** [comment]
First we have to install react-router-redux plus typings

```
npm install react-router react-router-redux --save
npm install @types/react-router-redux --save
```

Let's add syncbrowser to the store (main file)

```javascript
import { syncHistoryWithStore} from 'react-router-redux'
//(...)

let store = createStore(reducers);
const history = syncHistoryWithStore(hashHistory, store);
```

Now in the reducer index file (pseudocode), you have to update as well IAppState:

```javascript
import { routerReducer } from 'react-router-redux'

export const reducers =  combineReducers({
  sessionReducer,
  routing: routerReducer
});
```

**Comment by brauliodiez** [comment]
@martinguti95 sorry, about this task, do we have any update? @almecijam is working on a issue that needs this.

**Comment by martinguti95** [comment]
Sorry for the delay. I've made the PR #64  with the changes that are included in this issue

**Comment by brauliodiez** [comment]
Merged.
