### ISSUE TITLE
Move to common the string multiline trimmer (\r\n tabs spaces) and add specs

### ISSUE THREAD

**Issue by brauliodiez** [MasterLemon2016/LeanMood#29]
1. First check if enzyme already provides this  O :-)

Original:

```javascript
const plain = str => str.split(/(?:\r\n|\n|\r)/).map(line => line.trim()).join('');
```

Where to place it:

```
common
  parse
```

or @linuxonrails version

split map trim y join

**Comment by crsanti** [comment]
I've created some tests for this function: http://jsbin.com/kebuxa/7/edit?js,output
