### ISSUE TITLE
npm test throwing error (coverage), can be reproduced in travis

### ISSUE THREAD

**Issue by borjamaza** [MasterLemon2016/LeanMood#34]
![image](https://cloud.githubusercontent.com/assets/17314712/20797331/9ce01dea-b7da-11e6-9956-58c36bc87efc.png)

**Comment by brauliodiez** [comment]
Some addtional info:

https://github.com/karma-runner/karma-coverage/issues/157

**Comment by brauliodiez** [comment]
Found this

https://github.com/deepsweet/istanbul-instrumenter-loader/issues/32

But jumped back to 0.2.0 istanbul and it didn't work as expected.

I have just move to 'text' reporter meanwhile this issue gets corrected.
